tiann/KernelSU

- kernel/sucompat.c
Fixed the following error when compiling
ld.lld: error: undefined symbol: task_stack_page
>>> referenced by ld-temp.o
>>>               vmlinux.o:(sh_user_path)
> kernel: Include task_stack.h in sucompat.c

- kernel/ksu.c
From Kernel 5.11 it migrate to syscall_work instead of tif_*, so check for CONFIG_GENERIC_ENTRY and use syscall_work instead of TIF_SECCOMP
https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg2382193.html
> kernel: switch to syscall_work if CONFIG_GENERIC_ENTRY is enabled

- kernel/Kconfig
As KernelSU now support modules and mounting system as R/W using overlayfs, it's time to require overlayfs when trying to compile it.
> Kconfig : Make KSU depends on OVERLAY_FS

- userspace/ksud/src/module.rs
When executing module install scripts, KSU is set to "true"; when executing module post-fs-data scripts, KSU is set to "1". This may cause confusions so use the same value instead.
> ksud: use the same variable type in scripts

- kernel/selinux/sepolicy.h
Idea from @Dreamail
Before fix:
```
make[1]: 进入目录“/home/celica/kernel/out”
GEN     Makefile
CALL    ../scripts/checksyscalls.sh
CALL    ../scripts/atomic/check-atomics.sh
CHK     include/generated/compile.h
CHK     kernel/kheaders_data.tar.xz
CC      drivers/kernelsu/selinux/sepolicy.o
In file included from ../drivers/kernelsu/selinux/sepolicy.c:2:
In file included from ../drivers/kernelsu/selinux/sepolicy.h:4:
In file included from ../security/selinux/ss/sidtab.h:14:
In file included from ../include/linux/spinlock_types.h:13:
In file included from ../arch/arm64/include/asm/spinlock_types.h:12:
../include/asm-generic/qspinlock_types.h:24:3: error: unknown type name 'atomic_t'
atomic_t val;
^
../include/asm-generic/qspinlock_types.h:33:4: error: unknown type name 'u8'
u8      locked;
^ …
```
> Fix error for some non-GKI kernel source code

- .github/workflows/build-WSA-5.10.117-kernel.yml
1. The WSA kernel version has nothing to do with the Android version. Remove the Android version display
2. Merge x86_ 64 and arm64 strategy
> kernel: Change CI build for WSA-5.10.117

- kernel/Makefile
The original one can only override by `make EXPECTED_SIZE=123 EXPECTED_HASH=123`
> kernel: allow override EXPECTED_* by env

- kernel/sucompat.c
- task_stack() had been separated when it was in Linux 4.11, so let's do our migration when KernelSU facing the old version of kernel.
- See https://github.com/gregkh/linux/commit/f3ac60671954c8d413532627b1be13a76f394c49
- This allowed KernelSU to be complied into Linux 4.9 kernel after we did the backportation of selinux_state(), validated in SlightlyLookAround/kernel_for_vince.
> kernel: Migrate the reference of task_stack()

- manager/app/src/main/res/drawable/ic_launcher_background.xml
- manager/app/src/main/res/drawable/ic_launcher_foreground.xml
- manager/app/src/main/res/drawable/ic_launcher_monochrome.xml
- manager/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
The icon looks more modern when using themed icon on Android 12+
> manager: Add monochrome themed icon on Android 12+

- .github/workflows/build-kernel-5.10.yml
- .github/workflows/build-kernel-5.15.yml
We can get pub key hash by 
```
avbtool info_image --image boot.img
```
> ci: use custom key to sign official bootimgs

- website/docs/repos.js
Change _MI8SE(sirius) for LineageOS_ To _Xiaomi MI 8 SE(sirius)_
With a lot of tests, it also can use on Crdroid, PixelExperience and so on.
> website: Remove "For LineageOS" on MI 8 SE

- .github/workflows/ksud.yml
> ci: replace actions-rs/cargo with naive command

- kernel/Makefile
- kernel/allowlist.c
- kernel/apk_sign.c
- kernel/kernel_compat.c
- kernel/kernel_compat.h
- kernel/ksud.c
- kernel/selinux/rules.c
- kernel/selinux/selinux.c
- kernel/sucompat.c
- kernel/uid_observer.c
These changes make KernelSU work on kernel4.4 [link](https://github.com/F-19-F/android_kernel_oneplus_msm8998).
LINUX_VERSION_CODE macro changes have been vertied on 4.4 4.9 4.14.
For kernel 4.4,just pick two commits
* [introduce KernelSU](https://github.com/F-19-F/android_kernel_oneplus_msm8998/commit/2993524f2fe7fbd2eea28883ec9f36e86de50f85)
* [allow init exec ksud under nosuid](https://github.com/F-19-F/android_kernel_oneplus_msm8998/commit/3df9df42a659f489091445d813b8c0477215ae3a)
> kernel: changes for old Kernel

- kernel/allowlist.c
- kernel/core_hook.c
- kernel/kernel_compat.c
- kernel/kernel_compat.h
- kernel/uid_observer.c
On older kernel, kworker missing keyring from init process ,  and  this keyring is related to FBE , which causes filp_open return ENOKEY or other errors.To fix this,just install init's keyring to per kworkers.This works on Kernel 4.4 and 4.9.
> kernel: fix filp_open on older kernel's kworker

- kernel/selinux/selinux.c
* d77ab8d although fixed some typo, but since there is no include avc.h, this will cause the build to fail
* Error:
/mnt/HDD/fish/aospa/kernel/msm-4.9/drivers/staging/ksu/selinux/selinux.c:60:2: error: use of undeclared identifier 'selinux_enforcing'
selinux_enforcing = enforce;
^
/mnt/HDD/fish/aospa/kernel/msm-4.9/drivers/staging/ksu/selinux/selinux.c:81:9: error: use of undeclared identifier 'selinux_enforcing'
return selinux_enforcing;
^
2 errors generated.
Change-Id: I4cc8917b2b73ca467873222e02d498da8718988e
> kernel: selinux: Fix build error

- kernel/selinux/selinux.c
* Merged related changes in android-common-kernel-4.14.163 [1] Handle correct checks for older versions (below 4.14.163, 4.9, 4.4)
* fixes 14be7562, it is required in 4.14.163 kernel, it is not needed in 4.14.163 and later
[1]: https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commits/1cfd8419
Change-Id: Iade104312d058a249667ca836259d5608418bb55
> kernel: Correctly judge the version of selinux_state

- kernel/Makefile
.git is a text file while the module is imported by 'git submodule add'.
> fix  KSU_GIT_VERSION is not defined while importing KSU by 'git submodule add'

- kernel/selinux/rules.c
* [android-4.14-stable tree: https://github.com/aosp-mirror/kernel_common/commit/5d0939e1]
Change-Id: Ice92dd83df4c4f1ae272156cb57f95998e45819f
> kernel: Fix f6967d2c lost parameters after ack-linux 4.14.y (>=163)

- kernel/selinux/rules.c
- kernel/selinux/selinux.c
_selinux_state_ is backported to 4.9 kernel with the 4.9.212 release, use it to fix the build.
many thanks to @reallysnow for figuring this out.
inspired by https://github.com/ReallySnow/kernel_google_bluecross/commit/d7c2c5f02ad1ce89e746fa14f097ea71fdc4aadc
> use selinux_state for 4.9.212+

- kernel/include/ksu_hook.h
Then we don't have to do extern input_hook(...) ; input_hook(..) and just include header file and use input_hook(...) only
Like https://github.com/hac4us06/kernel_xiaomi_chime/commit/f39f4823a196c1cb66df10e96c93dfb97872a4c4
Not
https://github.com/hac4us06/kernel_xiaomi_chime/commit/0c491aca8a7c41c5d0b11616dccec6ab54e41082
> kernel: Add input hook to ksu_hooks.h

- kernel/Makefile
One should have git in PATH in order to build Android kernel.
Also it's weird that git is used in `setup.sh` without absolute path.
> kernel: use git from PATH

- kernel/selinux/rules.c
- kernel/selinux/selinux.c
4.9's last release aka 4.9.337 still needs the same fallbacks as 4.9.212 and breaks otherwise, upgrade this to fix compilation
Tested and working on POCO F1, 4.9.337
> selinux: Update 4.9 to the correct check

- userspace/ksud/src/installer.sh
https://github.com/tiann/KernelSU/commit/ee09b9f9f4c1b42da3af5cc4df96629e4f6c0745 修改了模块路径，installer.sh 没有修改，导致管理器无法刷新模块(安装/更新/卸载)状态
> ksud: Fix installer.sh modules path

- kernel/Makefile
Prevent failing to get KSU_GIT_VERSION when PATH contains space.
[Details](https://github.com/5ec1cff/my-notes/blob/master/mi-kernel.md#%E4%B8%80%E4%B8%AA%E7%BC%BA%E5%B0%91%E5%BC%95%E5%8F%B7%E5%BC%95%E5%8F%91%E7%9A%84%E8%A1%80%E6%A1%88)
> kernel: fix search git in path

- website/docs/repos.json
Hi, I have made yet another KernelSU integrated kernel for Redmi #K20Pro (#Raphael), based on a popular custom & optimized kernel called Bool-X in the community.
Forked source code: https://github.com/etnperlong/kernel_xiaomi_raphael_bool-x/tree/13.0-ksu
upstream source: https://github.com/onettboots/bool-x_xiaomi_raphael (thanks to @onettboots)
I have tested the KernelSU feature on this kernel, everything works fine.
> promotion: KernelSU integrated Bool-X kernel for raphael

- kernel/setup.sh
I think we can add tag selection commands in the setup.sh script, such as git checkout v0.5.1, to ensure the stability of use #379
> Ensure the stability of use

- kernel/setup.sh
Before fix:
```
[celica@arch msm-5.4]$ curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
++ pwd
+ GKI_ROOT=/home/celica/workdir/mvaisakh-kernel/kernel/msm-5.4
+ echo '[+] GKI_ROOT: /home/celica/workdir/mvaisakh-kernel/kernel/msm-5.4'
[+] GKI_ROOT: /home/celica/workdir/mvaisakh-kernel/kernel/msm-5.4
+ test -d /home/celica/workdir/mvaisakh-kernel/kernel/msm-5.4/common/drivers
+ test -d /home/celica/workdir/mvaisakh-kernel/kernel/msm-5.4/drivers
+ DRIVER_DIR=/home/celica/workdir/mvaisakh-kernel/kernel/msm-5.4/drivers
+ test -d /home/celica/workdir/mvaisakh-kernel/kernel/msm-5.4/KernelSU
+ cd /home/celica/workdir/mvaisakh-kernel/kernel/msm-5.4/KernelSU
+ git stash
没有要保存的本地修改
+ git pull
您当前不在一个分支上。
请指定您要合并哪一个分支。
详见 git-pull(1)。
git pull <远程> <分支>
``` …
> kernel: Fix pull when we are not currently on a branch

- kernel/selinux/Makefile
- kernel/selinux/rules.c
- kernel/selinux/selinux.c
- kernel/selinux/selinux.h
This checks `selinux_state` and `current_sid` supports in a raw way. Feels more reliable than the version checks.
Supersedes #401, fixes #280, fixes #400.
> selinux: use grep to check api supports

- README_CN.md
- README_TW.md
The credit link title of [genuine](https://github.com/brevent/genuine) in `README_CN.md` and `README_TW.md` is `true`.
> readme: fix credits link title of genuine project

- kernel/setup.sh
Use ../ instead of absolute path
> kernel: Use a better way to link submodule directory

- kernel/Kconfig
For those who want to Implement KernelSU Manually with KPROBES disabled.
When KPROBES Broken and Still enabled, this will causing Loop at splash logo even Already Manually Imported because this https://github.com/tiann/KernelSU/blob/842c0b674feaa4f6522452c8dc2ad2837f99892c/kernel/ksu.c#L57. And when KPROBES is disabled, KSU also will not compiled (I Know it'll still build if obj-y is set for KSU, but it's better to remove, who knows if someone set as obj-$(CONFIG_KSU)).
> kernel: Kconfig: Remove KPROBES dependancy

- userspace/ksud/src/mount.rs
fix https://github.com/tiann/KernelSU/issues/489
> ksud: use MS_RDONLY when mounting overlayfs

- kernel/ksu.c
- userspace/ksud/src/ksu.rs
Disabled by default.
To enable/disable use terminal with root.
To enable:
echo 1 > /sys/module/ksu/parameters/global_namespace_enable
To disable:
echo 0 > /sys/module/ksu/parameters/global_namespace_enable
Value will be reset to 0 (disabled) on reboot.
> Add option to enable global namespace

- kernel/Kconfig
1. List KSU as a "KernelSU" menu
2. Overlayfs[1] may be disabled for some early kernels(4.4.y), so choosing depends on OVERLAY_FS here is useless.
3. KSU_DEBUG is a bool option, it is not a module, fixed from tristate to bool.
4. Adjust the config order
[1]: github.com/LineageOS/android_kernel_xiaomi_msm8998/commit/dcc27641
Change-Id: I49c77ba30f0a8ed00efc44afef8a12f9ad039d7e
> kernel: Modify and adjust KernelSU Kconfig

- kernel/ksu.c
According to the instructions in #479, integrating kernelSU can not require enabling kprobes, but when manually integrating KernelSU in android kernel 4.4-4.9, the following error may appear:
In file included from /home/synaptic/android_kernel_oppo_sdm660/drivers/
/home/synaptic/android_kernel_oppo_sdm660/drivers/kernelsu/uid_observer.c:12:0:
/drivers/kernelsu/ksu.c:60:2: warning: #warning"KPROBES is disabled, KernelSU may not work, please check https://kernelsu.org/guide/how-to-integrate-for-non-gki.html"
[-Wcpp]
error, forbidden warning: ksu.c:60
make[3]: *** [/home/synaptic/android_kernel_oppo_sdm660/scripts/Makefile.build:282: drivers/kernelsu/uid_observer.o] Error 1
> change warning about disable kprobes

- kernel/allowlist.c
Split compiler_types.h from compiler.h only available for linux 4.14
> Fixup: build under linux 4.14

- kernel/selinux/Makefile
- Seen with Linux 4.14 kernel with error message:
In file included from ../drivers/android/kernelsu/selinux/sepolicy.c:1: In file included from ../drivers/android/kernelsu/selinux/sepolicy.h:6: In file included from ../security/selinux/ss/policydb.h:30: In file included from ../security/selinux/ss/avtab.h:26: ../security/selinux/include/security.h:240:10: error: use of undeclared identifier 'EIDRM'
return -EIDRM;
^
CC      drivers/base/transport_class.o
CC      kernel/rcu/update.o
../security/selinux/include/security.h:246:10: error: use of undeclared identifier 'ENOENT'
return -ENOENT;
^
> kernel/selinux: Need to force include errno.h sometimes

- website/docs/repos.json
RealKing kernel has included kernelsu officially, so I don't need to keep maintaining this fork.  With the consent of the author of the RealKing kernel, the maintainer information here is updated to his.
> website: Update unofficial device maintainer information

- kernel/ksud.c
Not all use GCC compiler kernel support __maybe_unused.Use __maybe_unused will cost compile error.  
Tested different versions of the kernel from versions 4.4 to 4.9.  
Test list:
4.4.x:Xiaomi 6 stock kernel and Huawei hi3660 Proto kernel
4.9.x:OnePlus 6/6T kernel(GCC vsrsion can't use  __maybe_unused,Clang Version can use  __maybe_unused),Huawei Pangu hi3660 Kernel and Xiaomi 8(Clang Version can use __maybe_unused) .
> ksud.c:Fix the issue of incompatible __maybe_unused in the GCC compiler kernel used in versions 4.4. x to 4.9. x.

- kernel/allowlist.c
> kernel: fix typo in allowlist.c

- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Home.kt
Just a small design fix, to make the Unsupported Warning text have the same font as the Working text.
> Remove fontFamily from the Unsupported Warning

- kernel/Makefile
- kernel/ksu.h
This patch modifies the following:
- Move the version addition logic in ksu.h to Makefile processing
- Print the current version number of KernelSU during make build
build test (normal):
buildlog:
HOSTCC  scripts/basic/bin2c Using .. as source for kernel -- KernelSU version: 11055
CHK     include/generated/utsrelease.h
UPD     include/generated/utsrelease.h
KernelSU software:
KernelSU Working Version: 11055 (v) Superusers: 0 Modules: 0
build test (missing .git file):
buildlog:
HOSTCC  scripts/basic/bin2c Using .. as source for kernel ../drivers/kernelsu/Makefile:23: "KSU_GIT_VERSION not defined! It is better to make KernelSU a git submodule!"
CHK     include/generated/utsrelease.h
CHK     scripts/mod/devicetable-offsets.h
KernelSU software:
KernelSU Working Version: 16 (v) Superusers: 0 …
> kernel: Modify KERNEL_SU_VERSION logic and behavior

- kernel/ksu.c
According to the instructions in Kconfig, when the `CONFIG_KSU_DEBUG` option is turned on, KernelSU will run in `debug mode` instead of the `debug version` mentioned in kernel/ksu.c.
> kernel/ksu.c:Fix word mistakes when enabling CONFIG_KSU_DEBUG

- userspace/ksud/src/installer.sh
This allows the Magisk design-compliant module boot script to access `$MODDIR/system/$part` while the mounted overlay still points to `/$part`
Fix https://github.com/tiann/KernelSU/issues/726
> ksud: symlink by relative path when handle partitions

- website/docs/repos.json
Some changes to repos.json:
- Redirect android_kernel_xiaomi_surya to kernel_xiaomi_surya: Because the original warehouse has changed android_kernel_xiaomi_surya to kernel_xiaomi_surya, this time the original address is 404
- Removed kernel repository information maintained by AkariOficial #754
> repos.json:Update repo info

- website/docs/repos.json
This pull request includes a modified LineageOS kernel with the implementation of KernelSU for POCO F3/Redmi K40/Mi 11X (alioth), adding them to the list of unofficially supported devices.
> [add device]: POCO F3/Redmi K40/Mi 11X (alioth)

- website/docs/repos.json
Custom kernel for Oneplus SM8250 devices with support of KernelSU (using the command : curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -)
Precompiled kernel can be found here : 
https://t.me/StellarisRelease (stable)
https://t.me/DawfukSpace (testing)
I have tested the KernelSU feature on this kernel, everything works fine.
Current version used : 11165
KernelSU Manager signature size: 0x033b
KernelSU Manager signature hash: 0xb0b91415
> [add device]: Oneplus8/8T/8P/9R (opkona)

- userspace/ksud/src/installer.sh
Fix the duplicate directory name error that occurs when the destination directory already exists while moving folders.
> Fix the directory pathname while moving directories

- kernel/kernel_compat.c
Use current_cred()->session_keyring to check whether session_keyring installed or not.
> Kernel: fix filp_open in kernel below 4.9

- manager/app/src/main/res/values-zh-rCN/strings.xml
- manager/app/src/main/res/values-zh-rHK/strings.xml
- manager/app/src/main/res/values-zh-rTW/strings.xml
- manager/app/src/main/res/values/strings.xml
* Avoid misunderstanding "The current kernel version %d is too low" Many people misunderstand that the version of the Linux kernel is too low, so the version of KernelSU is low and they go looking for a kernel with an upgraded version of the Linux kernel.
Correct the string of require_kernel_version to avoid misunderstanding,
Now let them look for the updated KernelSU version of the kernel.
(cherry picked from commit dcc4ad10f81b1531b551b2b44a3b9cbdc0e489e9) Change-Id: I4373b006d45ed98e02effa4556e8a9e8c0b70f14
> manager: Corrected "Kernel version" and "KernelSU version" string

- .github/workflows/gki-kernel.yml
- manager/app/src/main/cpp/ksu.cc
For android13 gki kernels, Google puts lots of unused file to kernel source tree, while the Github Action only has 14G disk size and the ci may fail because of "No space left on device". So we just delete unused files to make it build success.
> ci: Delete unused files for build to free disk space

- kernel/kernel_compat.c
* linux/uaccess.h is also required on 4.4 and 4.9
-- KernelSU version: 11184
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: 0xb0b91415
CC      drivers/kernelsu/kernel_compat.o
../drivers/kernelsu/kernel_compat.c:159:9: error: use of undeclared identifier 'USER_DS'
set_fs(USER_DS);
^
1 error generated.
make[4]: *** [../scripts/Makefile.build:314：drivers/kernelsu/kernel_compat.o] 错误 1
make[3]: *** [../scripts/Makefile.build:599：drivers/kernelsu] 错误 2
Change-Id: I19598c62a3ae901049ea99ef878fa5c1a15201fd
> kernel: Fix commit `7bdb8858` in Linux 4.9.y and Linux 4.4.y builds

- .github/workflows/build-debug-kernel.yml
- .github/workflows/build-kernel-a12.yml
For patch level 2023-07, sublevel is 177 https://android.googlesource.com/kernel/common/+/refs/heads/android12-5.10-2023-07/Makefile 
For patch level 2023-09, sublevel is 185 https://android.googlesource.com/kernel/common/+/refs/heads/android12-5.10-2023-09/Makefile
> [CI] Update Android 12 5.10 sublevel and patch level

- .github/workflows/build-debug-kernel.yml
- .github/workflows/build-kernel-a13.yml
- Bluejay running GrapheneOS is on Kernel version `5.10.187`.  
- Tried to flash other versions `5.10.xxx` and all went into bootloop. Unsure how this version would go
> feat(kernel): Add Kernel 5.10.187

- .github/workflows/build-kernel-wsa.yml
- WSA latest version: `2307.40000.6.0`
-> Kernel version: `5.15.104.2`
- Next kernel version: `5.15.104.3`
-> We haven't yet confirmed the release of this kernel.
> Fix WSA kernels

- kernel/sucompat.c
Otherwise we will rewrite paths for filenames that begins with `/system/bin/su`.
This fix copies one extra byte from userspace filename so that when we encounter filenames like `/system/bin/suasf`,
`/system/bin/su\0` gets compared with `/system/bin/sua`, which correctly prevents the `su -> sh` path rewriting.
Close #957
> Copy one extra byte from userspace filename

- kernel/allowlist.c
- kernel/apk_sign.c
- kernel/core_hook.c
- kernel/ksud.c
- kernel/manager.c
- kernel/selinux/rules.c
- kernel/selinux/selinux.c
- kernel/selinux/sepolicy.c
1. Adapt to low version Android init process
2. Add stop hook output
3. Fix output with missing line breaks
> kernel: Adapt to low version Android init process

- website/docs/repos.json
[PR](https://github.com/tiann/KernelSU/pull/1024) 中删除了两个，实际上还在只是换名字了，希望加上：
https://github.com/Vincent4440/noxious_kernel_xiaomi_sm8250 -> https://github.com/Vincent4440/android_kernel_xiaomi_sm8250
https://github.com/zharzinhoo/Kernel-Oriente-Cebu -> https://github.com/zharzinhoo/android_kernel_motorola_cebu
> 其他开发者适配的非GKI内核

- .github/workflows/build-kernel-a14.yml
修正artifact無法被導出的問題
[action](https://github.com/tiann/KernelSU/actions/runs/6597355879)
Annotations
1 warning
upload-artifacts
No files were found with the provided path: Image-android13*/*.img.gz. No artifacts will be uploaded.
> 讓artifact可以正確導出

- kernel/selinux/rules.c
This fixes that the Module Installer is stuck when installing any Modules on Kernel 4.4
> KernelSU: selinux: fix Modules install stuck on kernel 4.4

- kernel/ksud.c
在 #973 __never_use_envp 被改名为 envp 并使用。
这导致 GKI 版本一旦代码运行到 [213](https://github.com/tiann/KernelSU/blob/344c08bb79ba12b692016750cda363f9f3500182/kernel/ksud.c#L213) 行（或许只有 WSA 等类似情况会跑到这？），就会触发一个空指针解引用。
此PR意在修复此问题，且已在WSA上测试。
> kernel: fix null pointer dereference for some case

- website/docs/repos.json
Due to job changes, I no longer maintain this kernel. Therefore, I will delete this repo website link.
> Remove non-GKI kernel(Huawei P10) that are no longer maintained

- website/docs/public/templates/kernelmanager.root
- website/docs/public/templates/rootexploler.root
- The use of CAP_SYS_ADMIN can be avoided in Kernel Manager, but cannot be avoided in Root Explorer because it's needed for mounting RW/RO.
- Capabilities adjustment
- Fix template typo
> templates: Update templates and try to get rid with `CAP_SYS_ADMIN`

- website/docs/guide/how-to-integrate-for-non-gki.md
- website/docs/id_ID/guide/how-to-integrate-for-non-gki.md
- website/docs/pt_BR/guide/how-to-integrate-for-non-gki.md
- website/docs/ru_RU/guide/how-to-integrate-for-non-gki.md
- website/docs/vi_VN/guide/how-to-integrate-for-non-gki.md
- website/docs/zh_CN/guide/how-to-integrate-for-non-gki.md
- website/docs/zh_TW/guide/how-to-integrate-for-non-gki.md
1. Divide the patches into a separate file segment
2. Fix the ISO C90 grammar warning in fs/open.c
Conflict: JA_JP Folder does not do how-to-integrate-for-non-gki.md
Change-Id: I23a611eb937d9cb3da7a2d97046e0b57f1efc4d6
> website: Optimize the non-GKI page format and repair errors

- website/docs/repos.json
Add Huawei nova 2 (pic) device that is a non-GKI kernel (Linux 4.4), regularly build with Github Actions weekly. This kernel is based on LineageOS kernel.
> [add device]: Huawei nova 2 (pic)

- kernel/selinux/rules.c
Above kernel 6.4, there is no struct_avc member in selinux_state.
> kernel: adapt to kernel above 6.4

- website/docs/repos.json
[add device] pixel 3a
There is a usable ksu image for Pixel 3a, but it's obsolete and doesn't work with latest ksu manager
here is my fork with latest ksu
> [add device] pixel 3a

- website/docs/repos.json
crdroid现在使用了改造动态分区，所以我跟进上游也使用了改造动态分区。
> Device: Oneplus 6T and Oneplus 6

- kernel/selinux/selinux.c
> Correctly handle is_ksu_domain, close #972

- website/docs/guide/how-to-integrate-for-non-gki.md
Option does not match the corresponding patch.
> website: Fix patches display

- .github/workflows/build-kernel-a14.yml
Not released
https://android.googlesource.com/kernel/common/+/refs/heads/android14-6.1-2024-01
> ci: remove a14 6.1 2024-01

- website/docs/repos.json
合并之前没发现偏偏合并以后发现多了个https://
之前的合并请求关闭了，只能再开一个（）
> [非官方支持设备]修正K-Nel-M1721内核的仓库网址

- js/package.json
The package can not be imported into TS project without this option. [docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package)
> Add types in package.json

- .github/workflows/build-kernel-a14.yml
Since android14 5.15.137 (2024-01) was released with QPR3 Beta2 on Pixel 8(Pro)
> [CI][A14] a14-5.15 patch level 2024-01 and 2024-02

- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Install.kt
今天刷一个模块，刷入时要配置一些内容，然后发现每次输出我都得手动滑动一下才能看全内容，就很难受。气得我直接翻源码，就有了这个PR   :P
- 防止logContent在重组时丢失。
- 修复输出内容总是自动滚动到上次内容的最底部，而不是最新内容的最底部的f问题。
> manager: a small fix in InstallScreen

- kernel/selinux/sepolicy.c
EMUI 10 kernel version is 4.14.xxx.  
The SELinux of Huawei's modified EMUI10 kernel is still similar to the EMUI 9 version.   This commit not support HarmonyOS 2 based EMUI 10.
> kernel:Compatible with devices based on Huawei EMUI10

- website/docs/public/templates/nethunter.root
This app requires DAC_OVERRIDE, DAC_READ_SEARCH, SYS_PTRACE, SYS_ADMIN (for /data/local r/w) and SYS_CHROOT, SETGID (to run chroot and run it's processes)
Devices with NetHunter installed is already considered compromised due to lack of security features(like SELinux), therefore users are advised not to store private data
It's not really worth restricting more capabilities of the app.
> Add nethunter.root template

- .github/workflows/build-kernel-a13.yml
My Pixel 7a has a kernel version `5.10.177-android13-4-00003-ga7208022a7ea-ab1081582`, with a security patch of 2024-02, but the only available kernel build for that is security patch 2023-07 which causes a bootloop.
> [CI][A13] a13-5.10 patch level 2024-02

- .github/workflows/build-kernel-a14.yml
https://android.googlesource.com/kernel/common/+/refs/heads/android14-6.1-2024-03
android14-6.1-2024-03 已经发布
https://android.googlesource.com/kernel/common/+/refs/heads/android14-6.1-2024-03/Makefile
从 Makefile 来看依旧是 6.1.68
> ci: a14-6.1 patch level 2024-02 to 03

- kernel/kernel_compat.c
- kernel/ksud.c
input-event-codes.h:
Input: add input-event-codes header file (https://github.com/torvalds/linux/commit/f902dd893427eade90f7eaf858e5ff8b150a5a12) This was in 4.4-rc, so 4.4.0 or above has it else no.
aio.h:
fs: move struct kiocb to fs.h (https://github.com/torvalds/linux/commit/e2e40f2c1ed433c5e224525c8c862fd32e5d3df2)
Below this version, we need to explicitly include aio.h for struct kiocb This was in 4.1-rc, so 4.0 or below should do the include
uaccess.h, sched.h was present for long times, but 4.10 splited out to include/sched/ but the current ifdef is not including uaccess.h for lower versions than 4.4. Fix it.
> kernel: Make it compile on 3.18 (maybe older) kernels

- .github/workflows/build-kernel-a13.yml
My Pixel 7a March 2024 update has kernel version 5.10.189-android13-4-00012-g1217bb583cc5-ab11174560 and Android security update 2024-03
https://cs.android.com/android/kernel/superproject/+/common-android13-5.10-2024-03:common/Makefile
Thanks
> [CI][A13] a13-5.10 security date 2024-04

- kernel/core_hook.c
Its too spammy to be on non-debug mode.
> kernel: guard "umount for uid" logprint with CONFIG_KSU_DEBUG

- kernel/throne_tracker.c
The original logic was wrong and used 3 strlen()s for every file found, wasting cpu.
Optimize it by first comparing only the filename length, given we already know it,
and then strncmp() to compare with "base.apk"
Tested successfully on my Bandido Kernel (4.19)
> throne_tracker: Fix Manager sometimes not detecting KSU and optimize it

- manager/app/src/main/java/me/weishu/kernelsu/ui/util/LogEvent.kt
> Exclude minidump.gz when collecting xiaomi logs

- kernel/arch.h
- kernel/ksud.c
- kernel/sucompat.c
1. Replace `do_execveat_common` with `sys_execve` and `sys_execveat`
2. Replace `input_handle_event` with `input_event` and `input_inject_event`
Tested on android12-5.10-2024-04, android13-5.15-2024-04. android14-6.1-2024-04
> Hook syscalls and stable symbols

- kernel/throne_tracker.c
Hi,
This PR fixes deadlocks that I've noticed within my kernel, with some minor optimizations around it.
Thanks.
> Deadlock fixes

- kernel/throne_tracker.c
in kernel v4.7.10:
extern unsigned int __pure full_name_hash(const char *, unsigned int);
in kernel v4.8.0:
extern unsigned int __pure full_name_hash(const void *salt, const char *, unsigned int);
> kernel: fix throne_tracker uncompile-able on 4.4 kernel (issue #1771)

- website/docs/repos.json
* 随着KernelSU的快速发展，非 GKI 和 GKI 1.0的设备早晚是要被放弃的
* 可以说，KernelSU已经开始这么做了
* 所以，我决定移除K-Nel M1721中的KernelSU
> 从非官方支持设备中移除K-Nel-M1721

- kernel/selinux/selinux.c
AOSP sepolicy does not allow appdomain to open pts. Hence, convert devpts domain to ksu_file to allow any access.
> Convert devpts domain to ksu_file

- kernel/throne_tracker.c
fix https://github.com/tiann/KernelSU/issues/1800
> throne_tracker: skip iterate if failed to open dir

- userspace/ksud/Cargo.lock
- userspace/ksud/Cargo.toml
- userspace/ksud/src/boot_patch.rs
```console
_  __                    _ ____  _   _ 
| |/ /___ _ __ _ __   ___| / ___|| | | |
| ' // _ \ '__| '_ \ / _ \ \___ \| | | |
| . \  __/ |  | | | |  __/ |___) | |_| |
|_|\_\___|_|  |_| |_|\___|_|____/ \___/ 
- Unsupported platform
- Trying to auto detect KMI version for ./image.img
- Preparing assets
- KMI: android12-5.10
- Unpacking boot image
- Adding KernelSU LKM
- Repacking boot image
- Output file is written to
- /tmp/tmp.dzLsDK6iyj/kernelsu_patched_20240726_012936.img
- Done!
```
It can only auto-detect when the kernel name is `r"(?:.* )?(\d+\.\d+)(?:\S+)?(android\d+)"`, otherwise you should use `--kmi` flag to specified your KMI version.
> ksud(feat): Parse KMI from boot or kernel

- website/docs/public/templates/kernelmanager.root
* Following capabilities are removed as not commonly used on Kernel Managers:
- CAP_SYS_NICE
- CAP_PERFMON
- CAP_SYS_MODULE
- CAP_SYS_RESOURCE
* Added CAP_DAC_OVERRIDE to prevent read/write permission issues
> templates/kernelmanager.root: Adjust capabilities

- website/docs/repos.json
Add N0kernel and NOVA kernels to the unofficially supported devices section in the KernelSU website.
KernelSU isn't added in the [source of NOVA kernel](https://github.com/kvsnr113/xiaomi_sm8250_kernel), however his builds include KernelSU ones as it can be seen in his [releases repo](https://github.com/kvsnr113/nova_kernel_releases/releases).
> website/docs: add N0Kernel and NOVA kernels

- kernel/core_hook.c
On Android-x86 (or BlissOS) it initialize Android by using switch_root or chroot, when checking a path with dentry_path_raw() it will show the whole real path instead of the path that we want.
Relax the checking requirement by using strstr to look for "/system/packages.list" in the string instead of requiring the path to be "/system/packages.list"
This fixes #1783
> kernel: Relax dentry_path_raw compare in core_hook

- js/README.md
- js/index.d.ts
- js/index.js
- js/package.json
- manager/app/src/main/java/me/weishu/kernelsu/ui/webui/WebUIActivity.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/webui/WebViewInterface.kt
Add a `ksu.moduleInfo()` in JS.
resolves https://github.com/tiann/KernelSU/issues/1571
test module's index.html
The test module:
[moduleInfo_test.zip](https://github.com/user-attachments/files/17001977/moduleInfo_test.zip)
test module's result:
> js: add moduleInfo method

- manager/app/src/main/java/me/weishu/kernelsu/ui/webui/WebViewInterface.kt
Because the exit callback in js cleans up the ChildProcess, when the last callback of stdout is executed after the exit callback, an error like “emitData ReferenceError: spawn_callback_1727358276092_68 is not defined” will occur.
> api: spawn CallbackList use UiThreadHandler::runAndWait executor

- manager/app/src/main/java/me/weishu/kernelsu/ui/util/KsuCli.kt
Redmi Note 12 Turbo (marble) comes shipped with Android 13, but the baseline/kernel target version is Android 12.
```
[ro.board.api_level]: [31]
[ro.board.first_api_level]: [31]
[ro.product.first_api_level]: [33]
[ro.vendor.api_level]: [31]
Linux localhost 5.10.198-android12-9-00085-g226a9632f13d-ab11136126 #1 SMP PREEMPT Wed Nov 22 14:16:37 UTC 2023 aarch64 Toybox
```
Maybe we should use `ro.board.first_api_level` instead of `ro.product.first_api_level`, or the minimum value. But anyway, it's better to be consistent with ksud.
https://github.com/tiann/KernelSU/blob/2f9210b2e79338e7e7b1eb91878cada2b9a37ed6/userspace/ksud/src/boot_patch.rs#L407
> manager: detect init_boot with Android version in uname

- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/ExecuteModuleAction.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/util/KsuCli.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/viewmodel/ModuleViewModel.kt
- manager/app/src/main/res/values-zh-rCN/strings.xml
- manager/app/src/main/res/values/strings.xml
- manager/gradle/libs.versions.toml
- userspace/ksud/src/cli.rs
- userspace/ksud/src/defs.rs
- userspace/ksud/src/module.rs
Commits:
- manager: Add `action.sh` for user to manually trigger modules' functionality from manager
- manager: Optimize ModuleItem
- manager: uninstall button: TextButton -> FilledTonalButton
- Optimize `run_action` function
Commit Author & Thank:
- @lightsummer233
- @lingqiqi5211
- [APatch](https://github.com/bmax121/APatch)
Demo Show:
> manager: Add action.sh for user to manually trigger modules' functionality from manager

- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/AppProfile.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Install.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Settings.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/util/Downloader.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/util/KsuCli.kt
- manager/app/src/main/res/values-zh-rCN/strings.xml
- manager/app/src/main/res/values/strings.xml
- manager/gradle/libs.versions.toml
https://github.com/user-attachments/assets/69467e00-0af9-4d46-add8-e24e767462bd
Use `ContextCompat` in `DownloadListener`
Bump ksp to `2.0.21-1.0.26`
Misc changes (See the [commit](https://github.com/tiann/KernelSU/commit/1fb49d918a1f5bb76d1e70eb848ede36b2292cd9) directly)
> manager: Fix save log

- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/SuperUser.kt
By default there's an annoying behaviour for which the manager leaves the search filter after changing destination without even showing the search bar anymore. Fix that and reset the list to the top instead of leaving it at the searched app's height
https://github.com/user-attachments/assets/268672af-ced9-4293-81df-4e1c7ef33489
original behaviour
https://github.com/user-attachments/assets/b9b318cf-273a-4130-b199-712e99f6ed72
changed behaviour
Tested-by: backslashxx [118538522+backslashxx@users.noreply.github.com](mailto:118538522+backslashxx@users.noreply.github.com)
> manager: Reset search filter after moving from SuperUser destination

- website/docs/public/templates/wireguard.root
These two permission is absolutely required:
- CAP_NET_ADMIN is needed for modifying routes.
- CAP_NET_RAW is for modifying iptables.
When the app starts to set up a tunnel, it seems to execute "cat /sys/module/wireguard/version" to check if wireguard kernel module is loaded or not. Despite the permission seems okay, without CAP_DAC_READ_SEARCH it could not read the version number and threw an error in the application log.
CAP_DAC_OVERRIDE is needed optionally for installing Wireguard command line tools. It could be turned back off once the binaries have been copied.
> Create wireguard.root template

- manager/app/src/main/java/me/weishu/kernelsu/ui/MainActivity.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Home.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt
**Changes**
1. With the addition of the Action button the module card feels pretty bloated when all of them are present at the same time.
To improve it we can use icons only instead of text since they take less space; this also means adding an icon for Update and Uninstall buttons.
Below are displayed other possible behaviors when not all of them are present:
Since the Update button appears less frequently than the others, make it always display its text unless both Action and WebUI are present.
2. Minor change to avoid possible missclicks caused by smaller buttons. Enabling and disabling modules is pretty rare by itself and considering overlayfs isn't as fast as magic mount a missclick often feels pretty punishing.
3. The commit 7b3e732 readded transitions to all sections but I noticed …
> Minor UI improvements

- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/ExecuteModuleAction.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Flash.kt
The current implementation of KSU manager's output screen simply prints `[H[J` when the `clear` command is used (in both the flashing module & action button screen) instead of clearing the screen:
This limits the ability of shell scripts to purely textual & linear outputs, and prevents more flexible outputs such as a refreshing progress bar or even a progress circle for long running scripts. The current implementation moreover limits the output to 65536 bytes for the String `text`, causing the app to hang once this limit has been reached for scripts with more verbose outputs.
This PR fixes these issues by allowing for usage of the `clear` command in shell scripts to clear the screen. It works by checking if the current output line starts with "[H[J", which is the default output of the …
> Imitate terminal clear command in manager

- .github/workflows/release.yml
fix #2306
in release steps:
https://github.com/tiann/KernelSU/blob/f715af0688b95a4eed61e4f12c375f3b2666a6a6/.github/workflows/release.yml#L82
ksud-* is a directory instead of elf file:
https://github.com/tiann/KernelSU/actions/runs/11625295599/job/32377938534#step:6:1547
When new release published,it only give a info instead of give an error:
https://github.com/tiann/KernelSU/actions/runs/11625295599/job/32377938534#step:7:13
> ci: fix ksud release

- website/docs/public/templates/shizuku.root
previous settings only grant `DAC_READ_SEARCH` causing Shizuku unable to chown service executable and making it unable to work properly. `DAC_OVERRIDE` capability added to allow Shizuku to execute it's service after chown.
---
---
> templates/shizuku.root: Fix shizuku service unable to run properly

- kernel/core_hook.c
- When disabling Seccomp, ensure that current->sighand->siglock is held during the operation.
- Locking to ensure safe access and modification of the `cred` structure within the `escape_to_root` function.
---
I think this issue described in #2236 may have been caused by concurrent read-write access without proper locking.
> Improve seccomp disable && Add locking to protect cred modifications in escape_to_root

- .github/workflows/gki-kernel.yml
Based on the commit from [android.googlesource.com](https://android.googlesource.com/kernel/common/+/75f82c6a15c4188cbb32825892fc6ae3e95479f0%5E%21/), this change applies a patch to the bazel build system for source code that does not include this fix and is using glibc version 2.38 or later. This ensures that the build process does not encounter linkage errors related to undefined symbols such as __isoc23_strtol, __isoc23_strtoul, and __isoc23_strtoull.
> Apply patch for glibc 2.38 compatibility in bazel build system

- userspace/ksud/src/cli.rs
- userspace/ksud/src/su.rs
- userspace/ksud/src/utils.rs
Global namespace is usually used to publicly apply mounts so calling unshare after entering root namespace is not desired bahavior. This also keeps -M option same as Magisk.
> Don't unshare after entering global namespace

- kernel/allowlist.c
- kernel/core_hook.c
Previously all capabilities were overridden with 0xffffffffffffffff, which is
not what normal processes have. This causes PR_CAPBSET_DROP prctl
fail because it is dropping invalid caps. Fix it.
This fixes https://gitlab.com/kalilinux/nethunter/apps/kali-nethunter-app/-/issues/378.
Co-Authored-By: 5ec1cff <56485584+5ec1cff@users.noreply.github.com>
> Avoid unnecessarily overriding capabilities

- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt
Uninstalled module has no enabled interactions (e.g. run action script, open webui, update).
Disabled module cannot run action script or open webui.
> manager: Disable interactions for uninstalled & disabled module

- kernel/core_hook.c
fix adb shell cannot escape to root after https://github.com/tiann/KernelSU/pull/2381
> kernel: clear securebits

- manager/app/src/main/java/me/weishu/kernelsu/ui/component/profile/RootProfileConfig.kt
This is never implemented in kernel (and likely never will be), so let's remove it from UI for now to avoid misleading users.
> Hide namespace config in app profiles

- userspace/ksud/src/module.rs
This fixes the issue that module image will always exist even if there is no module to be loaded. Sadly we need to boot twice because we can only know module status after image is mounted.
> Drop module image if no module remaining

- manager/app/src/main/java/me/weishu/kernelsu/KernelSUApplication.kt
/data/local/tmp is never writable for normal apps, why previously it works is that Rust's temp_dir() gets path from env, and since A13, TMPDIR is set to app's cache dir. This is not the case for A12, so it breaks. Fix it by set TMPDIR ourselves.
> Provide TMPDIR for boot image repacking

- manager/app/src/main/java/me/weishu/kernelsu/KernelSUApplication.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/util/Downloader.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/viewmodel/ModuleViewModel.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/viewmodel/TemplateViewModel.kt
properly send `User-Agent` and `Accept-Language` to `updateJson` server, module developers can check `User-Agent` whether to send update to user and set user preferred language for changelog.
also added cache to reduce update server load
> feat: properly set OkHttp header

- kernel/core_hook.c
We need to call path_put() to decrease the refcount.
> Fix reference count leak in nuke_ext4_sysfs()

- kernel/core_hook.c
When the manager is already running, if other programs / kernel toggle the sucompat enable status, 
The manager "Disable SU Compat" toggle button can not work, kmesg print "cmd enable su but no need to change."
I think we should still return reply_ok when the syscall value is consistent with the kernel, which would fix the issue.
> kernel: fix sometimes sucompat can not toggle by manager

- kernel/core_hook.c
- kernel/ksu.c
- kernel/ksud.c
- kernel/sucompat.c
follow up to https://github.com/tiann/KernelSU/pull/2475#issuecomment-2680947145
> Revert "kernel: remove unused CONFIG guard becuase GKI kernel enable kprobe by default"

- website/docs/repos.json
On latest update, we've added support for Samsung Galaxy A04 (a04), which force me to change the repository name to avoid confusion.
> website: Update Galaxy A05 to Galaxy A05/A04 repository link

- website/docs/repos.json
Adding Unofficial Support for Samsung M30s (Non gki)
> [add device]: Samsung M30s (M307F)

- website/docs/repos.json
Adding Unofficial Support for Samsung Galaxy A15 4G (GKI)
> [add device]: Samsung Galaxy A15 4G (sma155f)

- .github/workflows/build-lkm.yml
- .github/workflows/gki-kernel.yml
To fix build error and sync from upstream
> ci: Update lkm kernel version

- manager/app/src/main/java/me/weishu/kernelsu/Natives.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/component/KsuValidCheck.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Home.kt
- manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Settings.kt
Without KernelSU installed, root-related features did not take any effect. So, better to hide it.
Improving this pr:
https://github.com/tiann/KernelSU/pull/2483
Also attempt to address this:
https://github.com/tiann/KernelSU/pull/2483#issuecomment-2692048907
Tested-by: Faris <90097027+rsuntk@users.noreply.github.com>
Co-authored-by: Rifat Azad <33044977+rifsxd@users.noreply.github.com>
> manager: hide root related features if kernelsu not available

- kernel/throne_tracker.c
When the manager UID disappears from packages.list, we correctly
invalidate it — good. But, in the very next breath, we start scanning
/data/app hoping to find it again?
This event is just unnecessary I/O, exactly when we should be doing less.
Apparently this causes hangups and stuckups which is REALLY noticeable
on Ultra-Legacy devices.
Skip the scan — we’ll catch the reinstall next time packages.list updates.
Signed-off-by: backslashxx <118538522+backslashxx@users.noreply.github.com>
> kernel/throne_tracker: we just uninstalled the manager, stop looking for it

- kernel/core_hook.c
- userspace/ksud/src/installer.sh
we move the folder out of system if it exists in real filesystem and it is not a symlink.
this is already supported on init_event.rs so only handle_partition logic was needed to make it happen
since KernelSU is using overlayfs, we need to move these out.
Signed-off-by: backslashxx <118538522+backslashxx@users.noreply.github.com>
> ksud/installer: /odm handling

- userspace/ksud/Cargo.lock
- userspace/ksud/Cargo.toml
zip-extensions does not export time and deflate64 features now.
> Update zip-extensions and set needed features for zip

- kernel/throne_tracker.c
Files in /data/app may be stacked on incremental fs, if user installs big apps from play store or adb shell. Performing I/O operation on it may results in long-time blocking. As KSU won't get installed in those ways, just avoid cross fs access.
> throne_tracker: avoid cross fs access

- kernel/throne_tracker.c
Skip directories that does NOT have the same magic as /data/app.
This is to avoid scanning incfs and any other stacked filesystems.
While this is way dumber, it's way cheaper.
no kern_path(), no missable path_put(), no ref handling.
This supercedes
`throne_tracker: avoid cross fs access (https://github.com/tiann/KernelSU/pull/2626)`
- upstream https://github.com/tiann/KernelSU/commit/0b6998b474ed00610bbf2d6679f853cef07af3b8
Signed-off-by: backslashxx <118538522+backslashxx@users.noreply.github.com>
> kernel: throne_tracker: avoid cross-fs traversal using s_magic check

- kernel/selinux/rules.c
When kernel is compiled with CONFIG_DEBUG_ATOMIC_SLEEP enabled, it prints the following splat in dmesg during post boot:
[ 6.739169] init: Opening SELinux policy
[ 6.751520] init: Loading SELinux policy
[ 6.894684] SELinux: policy capability network_peer_controls=1 [ 6.894688] SELinux: policy capability open_perms=1 [ 6.894690] SELinux: policy capability extended_socket_class=1 [ 6.894691] SELinux: policy capability always_check_network=0 [ 6.894693] SELinux: policy capability cgroup_seclabel=0 [ 6.894695] SELinux: policy capability nnp_nosuid_transition=1 [ 7.214323] selinux: SELinux: Loaded file context from: [ 7.214332] selinux: /system/etc/selinux/plat_file_contexts [ 7.214339] selinux: /system_ext/etc/selinux/system_ext_file_contexts [ 7.214345] selinux: …
> kernel: selinux: rules: Fix illegal RCU lock usage in apply_kernelsu_rules()

- userspace/ksud/Cargo.lock
- userspace/ksud/build.rs
- userspace/ksud/src/boot_patch.rs
- userspace/ksud/src/cli.rs
- userspace/ksud/src/debug.rs
- userspace/ksud/src/init_event.rs
- userspace/ksud/src/module.rs
- userspace/ksud/src/mount.rs
- userspace/ksud/src/profile.rs
- userspace/ksud/src/sepolicy.rs
- userspace/ksud/src/utils.rs
https://github.com/rust-lang/rust-clippy/blame/e1be06240d2be922d7cd20226ebb9b6d0051d311/clippy_lints/src/format_args.rs#L168
> ksud: make clippy happy

- manager/app/src/main/cpp/jni.cc
Add conditional logging to jni.cc for debug builds.
> Strip JNI debug logs on release build

- kernel/core_hook.c
Rethink about this patch, isolated process which directly forks from zygote is just like normal app, so there is no reason apps won't crash but Isolated process will. Also zygote reopens fd before actually fork, so it should be fine.
This reverts commit 2a1741de96a789957555053cf5a397cbef1eb3e4.
> Unmount isolated process which forks from zygote unconditionally
