tiann/KernelSU

kernel/ksu.c

use some symbols, such as filp_open , from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it

need to import namespace

---

.github/workflows/build-kernel-5.10.yml
.github/workflows/build-kernel-5.15.yml
.github/workflows/build-su.yml
scripts/ksubot.py

ci: update message hint

---

userspace/su/jni/Android.mk
userspace/su/jni/simple_su.c
userspace/su/jni/su.c

If we want to get KernelSU version by `CMD_GET_VERSION`, `root` must be allowed to be manager.
Thanks Ylarod for assistance!

userspace/su: implement basic features

---

README_CN.md
kernel/allowlist.c
kernel/apk_sign.c
kernel/ksu.c
kernel/sucompat.c

1. update README_CN.md
2. indent fixup

[skip ci] minor fixup

---

kernel/ksu.c

kernel: make kernel correctly response CMD_GRANT_ROOT

---

.github/patches/5.10/0001-Makefile-Use-CCACHE-for-faster-compilation.patch
.github/patches/5.15/0001-Makefile-Use-CCACHE-for-faster-compilation.patch
.github/workflows/build-WSA-5.10.117-kernel.yml
.github/workflows/build-kernel-5.10.yml
.github/workflows/build-kernel-5.15.yml

Signed-off-by: lateautumn233 <3487467850@qq.com>

ci: Use ccache

---

manager/app/src/main/AndroidManifest.xml

https://user-images.githubusercontent.com/103818282/213997718-b15bc9b2-b894-4149-8b3d-6fb15bbba33c.mp4
Reference: https://developer.android.com/guide/navigation/predictive-back-gesture#opt-predictive

Add support for predictive back gesture

---

kernel/ksu.c

```
#ifdef MODULE
extern struct module __this_module;
#define THIS_MODULE (&__this_module)
#else
#define THIS_MODULE ((struct module *)0)
#endif
```

kernel: run ksu_kprobe_init if build as module

---

kernel/Kconfig
website/docs/guide/how-to-integrate-for-non-gki.md
website/docs/id_ID/guide/how-to-integrate-for-non-gki.md
website/docs/vi_VN/guide/how-to-integrate-for-non-gki.md
website/docs/zh_CN/guide/how-to-integrate-for-non-gki.md

MODULES is required for KPROBE but some kernel disabled it.

website:Remind readers how to resolve dependencies for KPROBES

---

website/docs/guide/unofficially-support-devices.md
website/docs/vi_VN/guide/unofficially-support-devices.md
website/docs/zh_CN/guide/unofficially-support-devices.md

Chinese translated using Google Translate

docs: Adding Android-x86 kernel supported by me

---

.github/scripts/build_a12.sh
.github/scripts/build_a13.sh
.github/workflows/build-kernel-a12.yml
.github/workflows/build-kernel-a13.yml
.github/workflows/build-ksud.yml
.github/workflows/build-manager.yml
.github/workflows/gki-kernel.yml

1. update kernel ci
2. push ksud builds to `gh-ksud` branch
3. fix manager build

ci: update build

---

website/docs/repos.js

Change-Id: I1d68b41d74c9cf237b834d96c53a5949add2f4ba

website: Add Xiaomi MI 6 (sagit) and Xiaomi MIX 2 (chiron)

---

website/docs/repos.js

website:add RedmiK30 4G(phoenix)

---

website/docs/repos.js

Change-Id: Ide86c6ea2256b06390852d73dc0b79bc8ced4792

website: Merged MI 6 and MIX 2 information into one line

---

manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt

Proper way to fix #107

---

website/docs/repos.js

Add kernelsu support for MI 8 (dipper)

website: add Xiaomi 8 (dipper)

---

website/docs/.vitepress/locales/id_ID.ts
website/docs/id_ID/guide/unofficially-support-devices.md

website: fix missing pages in ID language

---

website/docs/.vitepress/locales/id_ID.ts

website: fix missing directory in ID language

---

website/docs/repos.json

Fix devices info error for unofficially supported devices.
#173 
PS: 都是我昨晚手贱惹的祸

website:fix devices info error

---

website/docs/id_ID/guide/unofficially-support-devices.md

website: update translation in ID language

---

manager/app/src/main/res/values-vi/strings.xml

a small edit on module_overlay_fs_not_available, this is my suggestion : https://github.com/tiann/KernelSU/pull/182/commits/e6e7b50a1a0ba381988b3872bc38776e23eed7ce

manager: vi_VN: small edit

---

.github/workflows/build-ksud.yml
userspace/ksud/Cargo.toml
userspace/ksud/src/apk_sign.rs
userspace/ksud/src/cli.rs
userspace/ksud/src/debug.rs
userspace/ksud/src/event.rs
userspace/ksud/src/ksu.rs
userspace/ksud/src/main.rs
userspace/ksud/src/module.rs
userspace/ksud/src/mount.rs
userspace/ksud/src/restorecon.rs
userspace/ksud/src/sepolicy.rs
userspace/ksud/src/utils.rs

These issues are mostly found by `cargo clippy -- -W clippy::pedantic`.

ksud: fix issues found by `clippy`

---

manager/app/src/main/res/values-in/strings.xml

manager: update translation ID language

---

website/docs/repos.json

[add device]：Pixel4XL

---

kernel/selinux/selinux.c

i didn't realize these typos in #181

kernel: selinux: fix more typos introduced in #166

---

manager/app/src/main/res/values-ja/strings.xml

Added Japanese language to KernelSU Manager

---

manager/app/src/main/res/values-in/strings.xml

manager: Update ID language translation

---

manager/app/src/main/java/me/weishu/kernelsu/ui/util/LogEvent.kt

manager: send app list in bug report

---

.github/workflows/build-WSA-5.10.117-kernel.yml

1. Use ubuntu-20.04
1. Use LLVM 12
1. Fix build cache
1. Fix KernelSU version

Fix WSA Kernel build

---

kernel/apk_sign.c

https://github.com/tiann/KernelSU/commit/e743722449147e3549fe282cf82994ec4518390b still not fix #252

kernel: make some compiler happy again

---

website/docs/guide/installation.md
website/docs/zh_CN/guide/installation.md

I think there is a misspell in document

website: Fix wrong directory name in document

---

manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt

The adjustment is as follows, the left is before the adjustment, the right is after the adjustment.
---
---

manager: make a small adjustment to module screen

---

kernel/setup.sh

some device tree has no new line in Makefile

kernel: add new line in driver Makefile

---

kernel/setup.sh

https://github.com/tiann/KernelSU/commit/30abd9e31043b47579a9f0453b780a9b1376d7f0#commitcomment-105526985

kernel: Makefile new line with posix compatible

---

userspace/ksud/src/event.rs
userspace/ksud/src/restorecon.rs

Incorrect se context will make module system broken

ksud: ensure ksud context when install

---

.github/workflows/build-WSA-5.1x-kernel.yml
.github/workflows/build-kernel-wsa.yml
.github/workflows/release.yml

Checks: https://github.com/Howard20181/KernelSU/actions/runs/4672228625

WSA Kernel update to 5.15

---

userspace/ksud/src/event.rs
userspace/ksud/src/mount.rs

This fixes https://github.com/Dr-TSNG/ZygiskOnKernelSU/issues/18

ksud: fix bind mount failed again

---

website/docs/repos.json

[add device]: Xiaomi 10S

---

manager/app/src/main/res/values-zh-rTW/strings.xml

Update Traditional Chinese
Optimize the text for easier reading

Update Traditional Chinese

---

manager/app/src/main/res/values-zh-rHK/strings.xml
manager/app/src/main/res/values-zh-rTW/strings.xml

@cracky5322 For zh-rTW with Android Style: 
> Log: 記錄(檔)
Developer: 開發人員
Access: 存取(權)
Support: 支援(For users) 支持(For devs)

Update zh-rHK and zh-rTW 

---

kernel/ksud.c

ksud.c : Include compat.h

---

manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Home.kt
manager/app/src/main/res/values-in/strings.xml
manager/app/src/main/res/values-ja/strings.xml
manager/app/src/main/res/values-ro/strings.xml
manager/app/src/main/res/values-ru/strings.xml
manager/app/src/main/res/values-uk/strings.xml
manager/app/src/main/res/values-vi/strings.xml
manager/app/src/main/res/values-zh-rCN/strings.xml
manager/app/src/main/res/values-zh-rHK/strings.xml
manager/app/src/main/res/values-zh-rTW/strings.xml
manager/app/src/main/res/values/strings.xml

If not present, the English page will be opened by default.

manager: Open guide in the current language if it exist

---

website/docs/zh_CN/guide/difference-with-magisk.md

document: fix typo

---

.github/workflows/build-kernel-wsa.yml

WSA: 5.15.94.1

---

website/docs/repos.json

Issue https://github.com/tiann/KernelSU/issues/498 closed without any explicit reason, so made a pull request.

[Add Device]: OnePlus 5/5T (cheeseburger/dumpling)

---

manager/app/build.gradle.kts
manager/app/src/main/java/me/weishu/kernelsu/profile/AppProfile.kt
manager/app/src/main/java/me/weishu/kernelsu/profile/RootProfile.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/MainActivity.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/component/SearchBar.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/component/SettingsItem.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/component/profile/AppProfileConfig.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/component/profile/RootProfileConfig.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/AppProfile.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/BottomBarDestination.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Home.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Install.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Settings.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/SuperUser.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/viewmodel/SuperUserViewModel.kt
manager/app/src/main/res/values/strings.xml
manager/gradle/libs.versions.toml
manager/gradle/wrapper/gradle-wrapper.properties

+ update deps
+ update app profile page
+ don't show su and module page if no root

manager: several updates

---

website/docs/.vitepress/locales/id_ID.ts
website/docs/.vitepress/locales/ja_JP.ts

Though it is a little not suitable？

a little change

---

.github/workflows/build-debug-kernel.yml
.github/workflows/build-kernel-a12.yml
.github/workflows/build-kernel-a13.yml

+ android13-5.10.168
+ android13-5.15.94

ci: upgrade android13 kernel version

---

website/docs/repos.json

Also update link device Xiaomi Poco X3 Pro

[add device]: Xiaomi Poco F1

---

README.md
README_CN.md
README_JP.md
README_PT-BR.md
README_TW.md

added README_PT-BR.md support as mentioned before, for Brazilian Portuguese.

added support(README.md) for Brazilian Portuguese

---

README_JP.md

Changed the installation link to Japanese one (build page is English)

Update Japanese readme

---

kernel/Kconfig

Kconfig:Update text information

---

.github/workflows/build-kernel-wsa.yml

Remove: 5.10.117.2
Change: 5.15.98.1 -> 5.15.98.**4**

Update WSA Kernel

---

scripts/ksubot.py

Increase the timeout duration and try to resolve the 'telegram.error.TimedOut: Timed out' issue when sending messages in a Telegram group.

ksubot.py: Increase timeout

---

kernel/setup.sh

ci: respect the CONFIG_KSU options

---

manager/app/src/main/res/values/strings.xml

Fixes https://github.com/tiann/KernelSU/issues/602

Update English translation

---

.github/workflows/build-debug-kernel.yml
.github/workflows/build-kernel-a12.yml
.github/workflows/build-kernel-a13.yml

* Add android12-5.10.177 & android13-5.10.177

ci: upgrade kernel branches

---

.github/workflows/build-kernel-arcvm.yml
kernel/ksud.c

All changes are tested on my fork (the Telegram error was fixed in 9b16150): https://github.com/supechicken/KernelSU/actions/runs/5287864543

Add CI workflow for ChromeOS ARCVM

---

.github/workflows/build-kernel-a12.yml
.github/workflows/build-kernel-a13.yml

Fix the version name of android13-5.15.74
Add android12-5.10.117

ci: update gki version

---

website/docs/repos.json

Update the link of the KernelSU kernel release repo of the device I maintain

repos.json: Update the link of the KernelSU kernel release repo of the device I maintain

---

.github/workflows/build-kernel-arcvm.yml
.github/workflows/build-kernel-wsa.yml

Don't set ref branch for properly check PR

ci: Fix checkout branch

---

website/docs/repos.json

The old one is outdated and unmaintained

repos.json: Updated repo link for Sony Xperia 1 II & Sony Xperia 5 II

---

userspace/ksud/src/installer.sh

Add back variable names for post-fs-data.d and service.d directories

Add boot script directory vars

---

website/docs/repos.json

Support Xiaomi Redmi Note 8 and 8T

---

.github/workflows/build-kernel-arcvm.yml
.github/workflows/build-kernel-wsa.yml
.github/workflows/gki-kernel.yml
kernel/Makefile

https://github.com/tiann/KernelSU/issues/739
https://github.com/tiann/KernelSU/issues/745
https://github.com/tiann/KernelSU/issues/752

CI: Support set manager signature size and hash

---

website/docs/repos.json

Support m30s

---

website/docs/repos.json

* i dont have any clue what i am doing...sory tian sur...hhh

Again add unofficial support Google Pixel 2/2XL

---

kernel/kernel_compat.c

kernel: fix build for gcc

---

manager/gradle/libs.versions.toml

This typo causes gradle sync failed

manager: fix dependency version reference

---

README_VI.md
website/docs/guide/module.md
website/docs/vi_VN/guide/app-profile.md
website/docs/vi_VN/guide/difference-with-magisk.md
website/docs/vi_VN/guide/faq.md
website/docs/vi_VN/guide/hidden-features.md
website/docs/vi_VN/guide/how-to-build.md
website/docs/vi_VN/guide/how-to-integrate-for-non-gki.md
website/docs/vi_VN/guide/installation.md
website/docs/vi_VN/guide/module.md
website/docs/vi_VN/guide/rescue-from-bootloop.md
website/docs/vi_VN/guide/unofficially-support-devices.md
website/docs/vi_VN/guide/what-is-kernelsu.md
website/docs/vi_VN/index.md

Update Vietnamese language for kernelsu.org and README_VI.md

Language Update

---

.github/workflows/build-kernel-wsa.yml

- Restore kernels
- 5.15.**94.2**: WSA: **2305**.40000.(4~6).0
- 5.15.**104.1**: WSA: **2306**.40000.4.0
- 5.15.**104.2**: WSA: **2307**.40000.6.0
This is because it is still being distributed by MS official.
- Optimize workflow
Unless there is a destructive update, all settings are the same, so there are many unnecessary descriptions.
Therefore, the next time the device code is changed or the kernel version is updated to higher than 5.15, the current configuration will be restored again.

Optimize for WSA

---

.github/workflows/build-kernel-a13.yml

add a13-5.15.131

---

website/docs/repos.json

... seems so. This include:
* Adding KernelSU support for Nokia 8/8 Sirocco (NB1/NLA/A1N)

Adding support for Nokia 8/8 Sirocco

---

docs/README.md
website/docs/index.md

Makes the project look considerably more professional and less like you've just stumbled upon a phishing page.

enhance grammar and language in landing pages (en)

---

website/docs/repos.json

https://github.com/Vincent4440/noxious_kernel_xiaomi_sm8250  404
https://github.com/SakuraNotStupid  301 > https://github.com/SakuraKyuo
https://github.com/Sanju0910  301 > https://github.com/sreeshankark
https://github.com/zharzinhoo/Kernel-Oriente-Cebu  404

repos.json: update source repo link

---

.github/workflows/build-kernel-a13.yml

android13-5.10-2023-10 : https://android.googlesource.com/kernel/common/+/refs/heads/android13-5.10-2023-10
android13-5.15-2023-10 : https://android.googlesource.com/kernel/common/+/refs/heads/android13-5.15-2023-10

[CI] Update Android 13 sublevel and patch level

---

.github/workflows/build-kernel-a12.yml
.github/workflows/build-kernel-a13.yml
.github/workflows/build-kernel-a14.yml
.github/workflows/build-kernel-arcvm.yml
.github/workflows/build-kernel-wsa.yml
.github/workflows/build-manager.yml
.github/workflows/build-su.yml
scripts/ksubot.py

This stop bot from re-login every run.

fix(bot): prevent flood wait by caching bot session

---

website/docs/repos.json

Change-Id: I7227a2afd01fda5684cdb28a9c4c1b2dc8ef8b65

[add device]: Realme 6 / 7 (RM6785)

---

docs/README_JP.md

docs: Update translation instructions in README: Japanese

---

docs/README.md
website/docs/.vitepress/locales/en.ts

added logo and  badges  help users quickly and easily identify what they need or want. And added missing webpage.

README.md: added logo and  badges

---

website/docs/repos.json

I would like to request you to update the details to my kernel as NeverSettle kernel is no longer under development & the developer has left development for it, Therefore, I would like to apply with my kernel.

Aviici: Apply for avicii maintainership

---

website/docs/repos.json

Remove device:non-GKI kernel(OnePlus 8 Serials) that are no longer maintained

---

website/docs/repos.json

I didn't have a lot of time to maintain,so I removed it.

device: Drop Pixel redbull

---

website/docs/repos.json

device: Remove Xiaomi Mi 9 (Cepheus)

---

manager/app/src/main/java/me/weishu/kernelsu/ui/util/LogEvent.kt

Fix typo in LogEvent.kt

---

userspace/ksud/src/ksu.rs

- When no gid is provided, use uid as gid.

ksud: su supports set gid and groups

---

userspace/ksud/src/cli.rs

Not creating new historical legacy

Remove `ksud path` to make xi and vvb happy

---

website/docs/repos.json

第一次构建内核，虽然狗屎，总比没有好（
等有空再清理一下更新仓库，现在能正常使用，也没太大问题

Add unofficial support for Galaxy Note9

---

kernel/selinux/selinux.c

Co-authored-by: weishu <twsxtd@gmail.com>

kernel: fix secctx mem leak

---

.github/workflows/build-kernel-a14.yml

Update build-kernel-a14.yml to add ANDROID14-6.1.68

---

website/docs/repos.json

Add an unofficial support device
I will follow the updates of KernelSU to maintain the kernel for a long time

[Add devices]Meizu M6 Note

---

website/docs/repos.json

Add unofficial support devices

[Add devices] Oneplus 7 Serials

---

website/docs/public/templates/shizuku.root

Shizuku only needs DAC_OVERRIDE to execute the script to start the Shizuku service.
Also added bengali translation for the name and description.

Added shizuku.root template

---

website/docs/repos.json

A repository still under maintenance

Update msm8998 in repos.json

---

website/docs/guide/faq.md

English Faq: add wrong storage size on some Samsung

---

website/docs/guide/how-to-build.md

First time Pr to this project, not sure if I done it in the correct format

Add docs about Android 14 Kernel

---

.gitattributes
manager/gradle/libs.versions.toml
manager/gradle/wrapper/gradle-wrapper.properties
manager/gradlew.bat

Upgrade Gradle and AGP

---

kernel/core_hook.c

My bad.
as reported by @AzusaHana on tg

fixup! Suggest non-gki kernel users to backport path_umount

---

.github/workflows/avd-kernel.yml
.github/workflows/build-manager.yml
.github/workflows/ksud.yml

https://github.com/LSPosed/LSPlugin/commit/f48f2fea59bb5717459593f63cc799d7f8724df0

Fix manager signature

---

kernel/core_hook.c

Fix missing semicolon

---

website/docs/public/templates/adaway.root
website/docs/public/templates/adb
website/docs/public/templates/cemiuiler.readproc
website/docs/public/templates/incompetent.root
website/docs/public/templates/kernelmanager.root
website/docs/public/templates/nethunter.root
website/docs/public/templates/rootexploler.root
website/docs/public/templates/shizuku.root
website/docs/public/templates/system

Sorry for the previous PR.
This fixes #1553

templates: fix italian templates language id

---

manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Flash.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt

| Before | After |
| :----- | :----- |
| ![Screenshot_20240330-183552](https://github.com/tiann/KernelSU/assets/93428659/b42b2e90-2d52-4d0f-964a-2288aeec3d8a) | ![Screenshot_20240330-183539](https://github.com/tiann/KernelSU/assets/93428659/8272cd5e-6bfc-4444-9bac-19d95cc4b9cb) |

manager: Fix round corner for Module Info Card

---

website/docs/repos.json

add realme 9 pro 5g and oneplus nord ce 2 lite

add device

---

.github/workflows/build-kernel-arcvm.yml

1. Add support for ChromeOS ARM64 ARCVM.
2. Optimization of intermediate variable naming.
3. Optimization of kernel version acquisition logic for file names, obtaining the kernel version directly from Makefile.

Add support for ChromeOS ARM64 ARCVM

---

website/docs/repos.json

* Update links for a52sxq and m52xq since BlackMesa123 stepped down and i took over for those devices as well
Change-Id: I9b35fdce65da74fa757d5b77a3819c3174e12160

[add device] Galaxy A52 and A72

---

website/docs/repos.json

I do patches now, https://codeberg.org/vyrine/android_vendor_extra/src/branch/main/patches/kernel_xiaomi_sm8250/0001-Implement-KernelSU.patch

device: remove POCO F3/Redmi K40/Mi 11X (alioth)

---

manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Home.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/util/Downloader.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/util/module/LatestVersionInfo.kt
manager/gradle.properties
manager/gradlew

- Updated the checkNewVersion function to return a LatestVersionInfo data class instead of a Triple.
- Defined default null value for LatestVersionInfo in case of failure.
- Improved readability and maintainability by replacing the Triple with a data class.
- Included version code, download URL, and changelog in the LatestVersionInfo data class.

Refactor checkNewVersion function to use LatestVersionInfo data class

---

manager/app/build.gradle.kts
manager/build.gradle.kts
manager/gradle/libs.versions.toml
userspace/ksud/Cargo.lock
userspace/ksud/Cargo.toml
website/package.json
website/yarn.lock

Corrections/edits and reviews always welcomed.
Migrate to Kotlin 2
Updated dependencies
Refreshed lock files

Update Dependencies and Migrate to Kotlin 2

---

kernel/allowlist.c

Failed to check app_profile version

ksud: [Fix] grant root to the shell in debug mode

---

kernel/allowlist.c

Revert "ksud: [Fix] grant root to the shell in debug mode"

---

.github/workflows/build-kernel-arcvm.yml

Probably fixes #1655, likely related
---
納悶為啥過了那麼久都沒人發現，我也是剛剛更新 kernel 發現 KSU 沒被偵測到才發現的。
果然 ChromeOS 就是沒人用啊 🤣

ci: Fix ARCVM workflow to adapt to the change of kernel/Makefile

---

manager/app/build.gradle.kts
manager/app/src/main/AndroidManifest.xml
manager/app/src/main/java/me/weishu/kernelsu/ui/MainActivity.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/component/Dialog.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/component/SearchBar.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/component/profile/RootProfileConfig.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/component/profile/TemplateConfig.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/AppProfile.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/BottomBarDestination.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Flash.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Home.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Install.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Settings.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/SuperUser.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Template.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/TemplateEditor.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/theme/Theme.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/util/LogEvent.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/util/SELinuxChecker.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/webui/WebUIActivity.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/webui/WebViewInterface.kt
manager/app/src/main/res/values-night-v27/themes.xml
manager/app/src/main/res/values-night/themes.xml
manager/app/src/main/res/values-v27/themes.xml
manager/app/src/main/res/values/themes.xml
manager/gradle/libs.versions.toml

Fix insets on Android 15
Bump dependencies
Migrate Compose Destination to v2
Ready for review now

manager: Insets stuffs for Android 15

---

manager/app/src/main/java/me/weishu/kernelsu/ui/screen/ExecuteModuleAction.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt

- This commit fix issue #2171
Tested-by: backslashxx <118538522+backslashxx@users.noreply.github.com>

manager: Fix not refreshing after action button was pressed

---

website/docs/repos.json

website: Remove device maintained by @rsuntk

---

manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/viewmodel/ModuleViewModel.kt
manager/app/src/main/res/values-zh-rCN/strings.xml
manager/app/src/main/res/values/strings.xml

module list will be sorted by options when these are enabled:
It will be very friendly and convenient  when manager has many modules.

manager: Add sort options on module's appbar

---

manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt

- This commit fixes issue tiann#2250
https://github.com/user-attachments/assets/19dcca12-cb34-4e6e-88b4-72c26c2773f3
Tested by: backslashxx <118538522+backslashxx@users.noreply.github.com>

manager: module: refresh after webui usage

---

website/docs/repos.json

Add non-gki kernel
Device: Samsung Galaxy F23 and M23

Add m23xq device kernel

---

.github/workflows/avd-kernel.yml

see https://forum.khadas.com/t/build-kernel6-1-fail-undefined-symbol-isoc23-strtoull/23432

use ubuntu-22.04 to build avd kernel

---

website/docs/repos.json

810a62f79549abb9a0aedf48f85c90d42eff7b9d

[Remove devices] daisy, sakura, ysl, sunny/mojito, fog/rain/wind

---

website/docs/repos.json

[add device]: Xiaomi Poco F6 (Peridot)

---

kernel/allowlist.c
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/AppProfile.kt
manager/app/src/main/res/values-zh-rCN/strings.xml
manager/app/src/main/res/values/strings.xml

This fixes https://github.com/tiann/KernelSU/issues/2416.

Allow toggling unmount setting for all apps

---

manager/app/src/main/java/me/weishu/kernelsu/KernelSUApplication.kt

fix: crash #2463

---

website/docs/guide/faq.md

Clarification on KernelSU device support and wording change in a few FAQs.

FAQ Edit regarding KernelSU support and wording change.

---

manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Flash.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/util/KsuCli.kt
manager/app/src/main/res/values/strings.xml

manager: allow multiple modules to be installed sequentially

---

website/docs/guide/faq.md

FAQ Slight spelling fix

---

manager/app/src/main/java/me/weishu/kernelsu/ui/screen/AppProfile.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/ExecuteModuleAction.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Flash.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Install.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Settings.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Template.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/TemplateEditor.kt

This fixes https://github.com/tiann/KernelSU/issues/2462.

Avoid popping back stack right after navigation

---

kernel/allowlist.c

This reverts commit bd24044ec3c8c14fd9efba209a9a1b73c328d4d5.

Set KSU_APP_PROFILE_VER for shell

---

userspace/ksud/src/su.rs

This fixes https://github.com/tiann/KernelSU/issues/2523.

Fix su --shell argument handling

---

.github/workflows/build-kernel-arcvm.yml

ref: https://github.com/tiann/KernelSU/actions/runs/14575050545/job/40879303805#step:2:416

ci: Update llvm version for chrome arcvm kernel build

---

manager/app/src/main/java/me/weishu/kernelsu/ui/viewmodel/ModuleViewModel.kt

Fix module update failures caused by spaces and other non Linux readable characters
Signed-off-by: ShirkNeko <109797057+ShirkNeko@users.noreply.github.com>

Add a formatting string for the update list #2556

---

kernel/core_hook.c

Revert "Handle unmount for isolated process correctly"

---

manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/SuperUser.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/viewmodel/ModuleViewModel.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/viewmodel/SuperUserViewModel.kt
manager/gradle/libs.versions.toml

* https://github.com/tiann/KernelSU/pull/2725#issuecomment-3237701851

manager: Support search module

---

kernel/core_hook.c

Revert "Unmount isolated process which forks from zygote unconditionally"

---

manager/app/src/main/java/me/weishu/kernelsu/ui/component/Dialog.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Module.kt
manager/app/src/main/java/me/weishu/kernelsu/ui/viewmodel/ModuleViewModel.kt
manager/gradle/libs.versions.toml

* display the changelog text in a ScrollView

manager: Allow module update info to scroll naturally
